config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cocktails, only: [:new, :create, :index, :show] do
    resources :doses, only: [:new, :create]
  end
    resources :doses, only: [:destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
# frozen_string_literal: true
class Cocktail < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
# frozen_string_literal: true
class Dose < ApplicationRecord
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]

  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
# frozen_string_literal: true
class Ingredient < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :doses
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]
  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  private
  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <h2>Liste des cocktails</h2>
  <div class="card">
      <% @cocktails.each do |cocktail| %>
      <p><%= link_to cocktail.name, cocktail_path(cocktail)%></p>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <%= f.button :submit%>
<% end %>
    </div>
  </div>
 <%= link_to "Back to all cocktails", cocktails_path %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h2><%= @cocktail.name %></h2>
      <% @cocktail.doses.each do |dose| %>
        <div class="card-category">
          <p><%= dose.ingredient.name%></p>
          <p><%=dose.description%></p>
          <%= link_to "🗑", dose_path(dose), method: :delete, data: { confirm: "Are your sure?"} %>
      <% end %>
    </div>
    <%= link_to "Add an ingredient and a dose", new_cocktail_dose_path(@cocktail), class: "my-button" %>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        <%= f.button :submit, class: "my-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 </head>

  <body>
    <%= yield %>
  </body>
</html>